DATA_CHANNELS = [
    XXXXXXXXXXXXXXXXXX,
    XXXXXXXXXXXXXXXXXX,
    XXXXXXXXXXXXXXXXXX,
    XXXXXXXXXXXXXXXXXX,
    XXXXXXXXXXXXXXXXXX,
    XXXXXXXXXXXXXXXXXX,
    XXXXXXXXXXXXXXXXXX,
    XXXXXXXXXXXXXXXXXX,
]
CLOCK_CHANNEL = XXXXXXXXXXXXXXXXXX

VOTES_REQUIRED = 5
PHRASE = "weenie hut general"
UP = "⬆️"
DOWN = "⬇️"
DEBUG = False

ICON_ON = "icon_on.png"
ICON_OFF = "icon_off.png"
NICKS_CSV = "nicks.csv"

VOTE_MESSAGE = XXXXXXXXXXXXXXXXXX
VOTE_CHANNEL = XXXXXXXXXXXXXXXXXX
GUILD = XXXXXXXXXXXXXXXXXX
GUILD_NAME = "guild name"

SENDER_TOKEN = XXXXXXXXXXXXXXXXXX
RECEIVER_TOKEN = XXXXXXXXXXXXXXXXXX
BOT_TOKEN = XXXXXXXXXXXXXXXXXX

CHANNELS = {
    XXXXXXXXXXXXXXXXXX: "channel name",
}
